### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by joker1007** [tomykaira/rspec-parameterized#23]
@tomykaira Please release v0.2.0, or give me a releasable privilege of rubygems

**Comment by tomykaira** [comment]
Added as a collab. Thank you for maintaining! :sushi:

**Comment by toshi-kawanishi** [comment]
:tada:

**Comment by joker1007** [comment]
Thanks :exclamation:

**Comment by joker1007** [comment]
released. :rocket:
