### ISSUE TITLE
Usage of variables in testcase name

### ISSUE THREAD

**Issue by PetrVales** [tomykaira/rspec-parameterized#27]
I'd like to do following:
```
where(:a, :b, :result) do
      [
        [1 , 2 , 3],
        [5 , 8 , 13],
        [0 , 0 , 0]
      ]
end

with_them do
      it "#{a} + #{b} = #{result}" do
        expect(a + b).to eq result
      end
end
```

But it crushes with error: 
```
`method_missing': `a` is not available on an example group (e.g. a `describe` or `context` block). It is only available from within individual examples (e.g. `it` blocks) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc). (RSpec::Core::ExampleGroup::WrongScopeError)
```
in rspec-core-3.4.2/lib/rspec/core/example_group.rb:667:

**Comment by jirutka** [comment]
Take a look at [@jnv's fork](https://github.com/jnv/rspec-parameterized), he implemented the feature you're asking for. You can use attribute `row` to access the table variables inside a `it` description. He didn't send PR though (I don't know why, it works well).

**Comment by joker1007** [comment]
Thanks for your report!
I am implementing this feature. #30
