### ISSUE TITLE
Support "||" syntax

### ISSUE THREAD

**Issue by sue445** [tomykaira/rspec-parameterized#34]
# Example (spock)
https://spockframework.github.io/spock/docs/1.0/data_driven_testing.html#_syntactic_variations

```groovy
class DataDriven extends Specification {
    def "maximum of two numbers"() {
        expect:
        Math.max(a, b) == c

        where:
        a | b || c
        3 | 5 || 5
        7 | 0 || 7
        0 | 0 || 0
    }
}
```

**Comment by joker1007** [comment]
Is this syntax alias of `|` ?

**Comment by joker1007** [comment]
Ah ... Ruby cannot define `||` method. because of it, this syntax is impossible by Refinement.
Parsing and dirty hack to sexp maybe realize it. But I don't want to add more black magic hacks

**Comment by sue445** [comment]
> Ruby cannot define || method

oh... :sob:

**Comment by joker1007** [comment]
I close it.
