### ISSUE TITLE
Release new version for Ruby 2.5.0

### ISSUE THREAD

**Issue by stanhu** [tomykaira/rspec-parameterized#48]
Thanks for the gem! When the `binding_of_caller` gem is in use, all rspec-parameterized tests fail in  Ruby 2.5 with the following message due to [this Ruby bug](https://bugs.ruby-lang.org/issues/15105):

```
RuntimeError:
  No such frame, gone beyond end of stack!
```

I've verified the `master` branch of this repository doesn't fail now that `binding_ninja` is used. Could you tag a new release?

**Comment by sue445** [comment]
@stanhu Thank you for report. I released `v0.4.1` :gem:  

Please check this.

**Comment by stanhu** [comment]
@sue445 Thank you! It works.
