### ISSUE TITLE
Add examples of https://github.com/tomykaira/rspec-parameterized/pull/62 to README

### ISSUE THREAD

**Issue by joker1007** [tomykaira/rspec-parameterized#63]
https://github.com/tomykaira/rspec-parameterized/pull/62

**Comment by Quintasan** [comment]
@joker1007 Thanks for your hard work on this gem. Would it be possible to tag a release with #62 without any docs for now? This is very useful, and I'd like to use that in my project.

**Comment by Quintasan** [comment]
@joker1007 Thanks for the quick turnaround on the release!
