### ISSUE TITLE
TableSyntax locks up test suite with Ruby 3

### ISSUE THREAD

**Issue by mttkay** [tomykaira/rspec-parameterized#69]
While looking to [migrate a GitLab component to Ruby 3](https://gitlab.com/gitlab-org/labkit-ruby/-/merge_requests/68), we encountered a problem that sends the Ruby VM into an endless loop when loading and executing tests that use `TableSyntax`. The problem only appears to materialize under specific conditions, but I was able to construct a minimum executable test case here: https://gitlab.com/mkaeppler/table-syntax-ruby3/-/blob/main/spec/context_spec.rb

We tracked down the problem to the following:

- TableSyntax relies on `binding_ninja`, which uses a C-extension to manipulate Ruby's method table: https://github.com/joker1007/binding_ninja/blob/master/ext/binding_ninja/binding_ninja.c#L55-L69, and prepends itself to the caller
- When a test is executed which:
  - loads code that also `extends` the `Object` class (such as `active-support/core-ext/object`)
  - uses the pipe operator `|` from `TableSyntax`
  - uses `expect` with block syntax (I have found no explanation for this yet -- it could be a red herring -- but if I remove this expectation from the test the problem does not materialize)

then Ruby 3 will spin forever in `search_method` looking for the `|` operator while traversing the superclass chain: https://github.com/ruby/ruby/blob/v3_0_1/vm_method.c#L969-L976

I'm not totally sure yet how all of this comes together for this issue to materialize, but it is reproducible using the test case I linked (just `bundle exec rspec`).

The `binding_ninja` extension looks very sketchy. If there is a way to replace this with some equivalent pure Ruby solution like `binding_of_caller`, I think that would address this problem.

**Comment by sue445** [comment]
@mttkay This is Ruby's bug and fixed at Ruby 3.0.2

* https://bugs.ruby-lang.org/issues/17494
* https://github.com/ruby/ruby/commit/d47df50678b00bd622e6be474031204ed2e52b31

Can you use Ruby 3.0.2?

**Comment by mttkay** [comment]
Oh yes! Not sure how I missed that, I had searched for problem reports like this. Thanks! Will report back to see if Ruby 3.0.2 works, we were targeting 3.0.1 :+1:

**Comment by mttkay** [comment]
3.0.2 indeed solves this. Sorry for the noise!
